1. Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [23]:
N = 10
np.arange(N-1, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

2. Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [33]:
N = 10
a = np.diag(np.arange(N-1, -1, -1), k=0)
print(a)

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [32]:
np.trace(a)

45

3. Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [34]:
a = np.array([[3, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

In [35]:
from numpy import linalg

In [36]:
linalg.solve(a, b)

array([ 0.63636364,  3.78787879, -5.48484848])

4. Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем. На сайт заходит очередной посетитель, о покупках которого известно следующее. Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [37]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
)

In [38]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [65]:
next_lenght = np.linalg.norm(next_user_stats)
cosine = []

for user in users_stats:
    user_length = np.linalg.norm(user)
    cosine = np.append(cosine, np.dot(user, next_user_stats) / (user_length *next_lenght))

print('максимальное косинусное расстояние', np.max(cosine))
print('индекс самого похожего пользователя', np.argmax(cosine))


максимальное косинусное расстояние 0.9486832980505138
индекс самого похожего пользователя 7
